### ISSUE TITLE
Add support for decompilation of Mach-O files

### ISSUE THREAD

**Issue by s3rvac** [avast-tl/retdec-idaplugin#11]
[RetDec](https://github.com/avast-tl/retdec) has a basic support for decompilation of Mach-O files. However, when I try to decompile a Mach-O file via the IDA plugin (e.g. [this one](https://github.com/avast-tl/retdec-regression-tests/raw/master/features/macho/hello.x86.clang.macho)), the plugin fails with the following error:
```
Retargetable Decompiler version 0.4 cannot decompile this input file.
```
IDA loads the input Mach-O file just fine. It would be nice if the IDA plugin supported the same file formats as RetDec.

**Comment by Maroc-OS** [comment]
The plugin actually is a mass and need a lot of work, it works sometimes and give strange errors must of times. like decompiling a PE library says always function must be selected. am on macOS btw.

For Mach-O i started working on it and ida crash's with exception start is greater then end.

followed the problem and found that it comes from : 

`void ConfigGenerator::generateFunctions()
`
fnc->end_ea == 0 when printing it.

fixed that part (ugly hack to follow fix ups) and come to same error on function : 

`void ConfigGenerator::generateSegmentsAndGlobals()
`
seg->end_ea == 0 when printing it.

File : config_generator.cpp

**Comment by Maroc-OS** [comment]
Sorry I found that I was using normal plugin as ida pro 64 bit ☝️.

Support for ARM is there already. Should I send a patch? I saw my pull requests even not reviewed or commented.
