### ISSUE TITLE
Not works. IDA 6.8 plugin

### ISSUE THREAD

**Issue by Karaulov** [avast-tl/retdec-idaplugin#17]
I just try to use it for test ( download retdec and this plugin, and ida 6.8, for test! )

Got error: 
---------------------------
Warning
---------------------------
Decompilation is not properly configured.
Either decompile.sh must be in system PATH,
or path to decompile.sh must be provided in configuration menu,
or API key and URL must be set.
---------------------------
OK   
---------------------------

![z7ijwq1 1](https://user-images.githubusercontent.com/6445336/36947677-6a5b5442-1fe0-11e8-96cd-f7782069e96a.png)

![ootw3ih 1](https://user-images.githubusercontent.com/6445336/36947680-6e7d32e8-1fe0-11e8-99c1-8cf5f4e3bcd6.png)

![mhmkqsj 1](https://user-images.githubusercontent.com/6445336/36947690-86185e0a-1fe0-11e8-8103-2f543f527fe2.png)

**Comment by Karaulov** [comment]
I tried to set "win" in config.sh (29 line). 

Now get error :
![1km5x8p 1](https://user-images.githubusercontent.com/6445336/36948908-70bb5bf4-1ff2-11e8-83ba-bc394399a3d9.png)

**Comment by Karaulov** [comment]
```
##### Trying to unpack D:/IDA_Disassembler_6.8/infile.dll into D:/IDA_Disassembler_6.8/infile.dll-unpacked.tmp by using UPX...
RUN: upx -d D:/IDA_Disassembler_6.8/infile.dll -o D:/IDA_Disassembler_6.8/infile.dll-unpacked.tmp
/cygdrive/d/IDA_Disassembler_6.8/retdec/retdec/bin/unpack.sh: line 122: upx: command not found
##### Unpacking by using UPX: nothing to do
'. Supported architectures: Intel x86, ARM, ARM+Thumb, MIPS, PIC32, PowerPC.

```

**Comment by Karaulov** [comment]
problem in cygwin ,need instal msys2. 

How to use retdec without ida?)))  (Any freeware gui for retdec ?)

**Comment by s3rvac** [comment]
> problem in cygwin ,need instal msys2.

Yes. Although the current `master` branch of RetDec can run on Cygwin, we suggest using MSYS2. The recommendation to use MSYS2 is also in the build and use instructions.

> How to use retdec without ida?))) (Any freeware gui for retdec ?)

Apart from the IDA plugin, there is no GUI, so you will have to run it from an MSYS2 terminal ([instructions](https://github.com/avast-tl/retdec#windows)).
