### ISSUE TITLE
Terminating plugin's thread in IDA does not terminate spawned decompilation process

### ISSUE THREAD

**Issue by PeterMatula** [avast-tl/retdec-idaplugin#20]
It is not enough to kill (`qthread_kill()`) decompilation thread using IDA SDK API. The decompilation process (`retdec-decompiler.sh` execution) which was created is not terminated.

I tried to use SDK's API for processes, but no luck so far. The matter is more compilated, because `retdec-decompiler.sh` itself launches other processes.

**Comment by Maroc-OS** [comment]
The code that handle this is not working good, it hangs sometimes don’t know why maybe when force closing ida pro. The code try to kill the running process blindly, and should use some kind of ways to detect if it’s really working not only look for variable if true or false.

**Comment by PeterMatula** [comment]
This will probably be easier to solve once bash scripts are rewritten to Python.

**Comment by PeterMatula** [comment]
Fixed in 3534c6ad56029551aabe01db03c5523f8f3769ce, 726e7012f693cf995441214162435fc647c0cd4c, and d2a299815bc5f0cc4f66d8b266e3037cc7e3fc36.
