### ISSUE TITLE
Create 64-bit address space version of RetDec IDA plugin

### ISSUE THREAD

**Issue by PeterMatula** [avast-tl/retdec-idaplugin#21]
Right now, we have only one plugin version for 32-bit address space (which is itself a 64-bit library, see [explanation](https://www.hex-rays.com/products/ida/7.0/docs/api70_porting_guide.shtml)). It should be possible to also create a 64-bit address space version, which would for now decompile only 32-bit binaries (until we add support for some 64-bit architectures).

**Comment by Maroc-OS** [comment]
I think i have a working version of it. just need to be sure it's working great. i can attach two plugins for macOS 64bit normal version and ea64 one built with `cmake .. -DIDA_SDK_DIR=$IDA_SDK_DIR -DEA64=1` if you wanna analyse and test them.

**Comment by PeterMatula** [comment]
I don't really have a macOS machine to test on. But if it works on macOS, it should work on Linux and Windows as well? What did you have to do to get it working? I did not research this much, so at the moment, I have no idea if you just build it differently, or you need to change the code as well.

**Comment by Maroc-OS** [comment]
i have updated the build system to support that and really quick changes on code.
