### ISSUE TITLE
There is no "retdec-idaplugin.sln" file。

### ISSUE THREAD

**Issue by ntzwq** [avast-tl/retdec-idaplugin#23]
There is no "retdec-idaplugin.sln" file。

**Comment by PeterMatula** [comment]
Well, this is not a very detailed issue description - more like an example how an issue should not look like.

But anyway, where do you expect `retdec-idaplugin.sln` to be? Did you run `cmake .. -DIDA_SDK_DIR=<path> -G<generator>`? `retdec-idaplugin.sln` is not in the repository, it gets created by `cmake` in the `build` directory. If you run `cmake` and it is not there, then this indeed is a problem.

**Comment by ntzwq** [comment]
TKS
