### ISSUE TITLE
loading of config failed: entryPoint must be an uint64

### ISSUE THREAD

**Issue by say2** [avast-tl/retdec-idaplugin#24]
current plugin make idb.json's entryPoint component in hex string like "entryPoint" : "0x400c00",
but retdec only recognize uint64

RUN: /c/Users/Home/Desktop/b/retdec-v3.0-windows-64b/retdec/bin/fileinfo -c C:/Users/Home/Desktop/b/login.cgi.c.json --similarity C:/Users/Home/Desktop/b/login.cgi --no-hashes=all --crypto /c/Users/Home/Desktop/b/retdec-v3.0-windows-64b/retdec/bin/../share/generic/yara_patterns/signsrch/signsrch.yara
Input file               : C:/Users/Home/Desktop/b/login.cgi
File format              : ELF
File class               : 32-bit
File type                : Executable file
Architecture             : MIPS (MIPS I Architecture)
Endianness               : Big endian
Entry point address      : 0x400c00
Entry point offset       : 0xc00
Entry point section name : .text
Entry point section index: 8
Bytes on entry point     : 03e0002104110001000000003c1c0005279caf34039fe0210000f8218f84807c8fa5000027a600042401fff803a1e82427bd
Detected tool            : GCC (4.5.4) (compiler), 80 from 183 significant nibbles (43.7158%)
Error: loading of config failed: entryPoint must be an uint64 value @ line = 26, column = 17

**Comment by PeterMatula** [comment]
You are probably using plugin version 0.5 with RetDec version 3.0. You must use version 3.1. I have updated user guide (Section 2.2) to make this clear.

In future, we would like to distribute RetDec itself together with RetDec IDA plugin, so it will be easier for the users.
