### ISSUE TITLE
"Decompilation is not properly configured" but it actually is

### ISSUE THREAD

**Issue by BullyWiiPlaza** [avast-tl/retdec-idaplugin#26]
I downloaded [`retdec 3.1` for Windows](https://github.com/avast-tl/retdec/releases) and unpacked it to `C:\retdec\bin`. I also added `C:\retdec\bin` to the `PATH` system variable. When I open a `cmd` shell and type `retdec-decompile.sh` the command is found and works as expected.

Furthermore I downloaded the `IDA` plugin `0.5` from [here](https://github.com/avast-tl/retdec-idaplugin/releases/tag/v0.5) and extracted the `retdec.dll` to the `IDA` plugins directory: `C:\Program Files\IDA 7.0\plugins`.

When I load up `IDA` and press `CTRL + D` to decompile, it shows me the following warning:
![image](https://user-images.githubusercontent.com/7620135/41809931-e0ace50e-76f5-11e8-888e-a66652324d0a.png)

This appear to be wrong, since I configure my `PATH` environment variable already so I click `OK`. The next dialog asks me to select the `retdec-decompiler.sh` file so I do that and click `Open`:
![image](https://user-images.githubusercontent.com/7620135/41810411-1ad4b524-76fe-11e8-91a1-8c82e97d1497.png)

Again, the `Decompilation is not properly configured` opens so it is stuck in an endless loop.

I'm not sure what I'm doing wrong or if this is a bug but how can I fix it?

I'm using the regular `IDA Pro 7.x` and not the free version. [Also I'm using a custom `IDA` plugin](https://github.com/avast-tl/retdec-idaplugin/issues/3) so I'm also getting the following warning:
![image](https://user-images.githubusercontent.com/7620135/41810443-a5278b66-76fe-11e8-965d-0f86853c3f6a.png)
I'm not sure if this matters but it might be worth to be mentioned regardless.

**Comment by PeterMatula** [comment]
Yes, it seems you are doing everything right - so it it hard to say, what is wrong. Lets try two things:
1. Can you try it with some binary that does not use custom IDA loader? This should not cause the described problem, but who knows. Just try it with as simple binary as possible.
2. If it still does not work (probable), can you try running RetDec from `cmd.exe` the same way the plugin does (it uses `sh`)?
`sh retdec-decompiler.sh --help`
`sh retdec-decompiler.sh simple-binary.exe`

**Comment by BullyWiiPlaza** [comment]
1. Using a simple binary (`32-bit Windows DLL`) in `IDA` also fails with the same problem (but I don't get the custom loader warning)
2. From `cmd.exe` it works but I just used `retdec-decompiler.sh simple-binary.dll` instead of the prepended `sh` since the `sh` command is not installed and it doesn't seem to be needed though.

With `win-bash`:
```
>C:\shell\sh.exe retdec-decompiler.sh simple-binary.dll
C:\Users\User\AppData\Local\Temp\191776.201428.inc.sh2: readlink: command not found
retdec-decompiler.sh: ./retdec-utils.sh: No such file or directory
retdec-decompiler.sh: syntax error near unexpected token `<<<'
retdec-decompiler.sh: retdec-decompiler.sh: line 184: `                 IFS='-' read -a vs <<< "$r"  # parser line into array'
```
I might be doing the later wrong but since I'm running `Windows`, `readlink` doesn't exist (it's a `Linux` command). Also I'm not sure why the `IDA` plugin uses `sh` when it works from `cmd.exe` without it.

**Comment by Tiemichael** [comment]
I am facing the exactly same issue as outlined in the 1st post.
(Windows 10/64, most recent IDA Pro, retdec and plugin, following all instructions from the Github pages)

`C:\Users\Michael>sh  retdec-decompiler.sh test.exe
/c/retdec/bin/retdec-decompiler.sh: line 23: ./retdec-utils.sh: No such file or directory`

`C:\Users\Michael>bash retdec-decompiler.sh test.exe
/c/retdec/bin/retdec-decompiler.sh: line 23: ./retdec-utils.sh: No such file or directory
/c/retdec/bin/retdec-decompiler.sh: line 169: get_realpath: command not found
/c/retdec/bin/retdec-decompiler.sh: line 170: get_realpath: command not found `

**Comment by Maroc-OS** [comment]
Fixed here : https://github.com/avast-tl/retdec-idaplugin/pull/27/commits/c195e41bd8bd027894e7e29cf27dea1196c5c80d pull request here : https://github.com/avast-tl/retdec-idaplugin/pull/27

**Comment by PeterMatula** [comment]
I think the problem is the missing `sh` (i.e. missing MSYS2). Right now, it is a bit tricky to set up everything correctly. Section 2.2 of plugin's user guide says you need a properly installed standalone RetDec. The [instructions](https://github.com/avast-tl/retdec/blob/3eaa0eaf9b27bee605786702784c4a1cecea3bc6/README.md#installation-and-use) to follow say to install and configure MSYS2 on Windows. Then, you should have both `sh` and `readlink` (and a bunch of other stuff).

Standalone RetDec might be working on your system even without MSYS2, but it does not on all Windows systems. That is why the plugin is explicitly calling `sh` (MSYS2) at the moment. If the MSYS2 is installed and in the path, it should work for all.

Try to install MSYS2.

There is already a [pull request](https://github.com/avast-tl/retdec/pull/338) that rewrites all bash scripts to Python. Once this is finalized and merged, the whole process should be much simpler - no MSYS, only Python. We will definitely create a new release, maybe even an all in one that contains both RetDec and plugin and will not need to be configured much (at all?).

**Comment by Tiemichael** [comment]
Thanks for your reply.
Not sure if I understand correctly, but when I use 'MSYS2' a MSYS-shell opens. 
C:\msys64\mingw64\bin;C:\msys64;C:\msys64\usr\bin; are included in my path.

**Comment by BullyWiiPlaza** [comment]
After installing `MYS2` and adding `C:\msys64\usr\bin;C:\msys64;C:\msys64\usr\bin` to the `PATH` it works now for me now. I also agree that `Python` would be better.
