### ISSUE TITLE
Decompilations fail with "launch_process(...) failed with error code 1"

### ISSUE THREAD

**Issue by perfectswpuboy1** [avast-tl/retdec-idaplugin#37]
![ida_CuwbU5pEO4](https://user-images.githubusercontent.com/356742/54661518-7e7c9100-4b15-11e9-86b4-0c0b93f7579b.png)

**Comment by PeterMatula** [comment]
Can you successfully run RetDec (`retdec-decompiler.py`) from command line - not via IDA?

I.e. gen you try the following:
* `python retdec-decompiler.py --help`
    * In your environment probably something like this (I'm guessing from the paths in that error message, maybe you will have to fix it a little bit):
    `C:\Users\x230\AppData\Local\Programs\Python\Python35-32\python.exe D:\GitHub\retdec-v3.3-windows-32b\retdec\bin\retdec-decompiler.py --help`
* `python retdec-decompiler.py x86_crackme_hash.exe`
    * `C:\Users\x230\AppData\Local\Programs\Python\Python35-32\python.exe D:\GitHub\retdec-v3.3-windows-32b\retdec\bin\retdec-decompiler.py D:\examples\x86_crackme_hash.exe`

If it works, we will try some more things. If it does not, please paste here what is says.

**Comment by perfectswpuboy1** [comment]
> Can you successfully run RetDec (`retdec-decompiler.py`) from command line - not via IDA?
> 
> I.e. gen you try the following:
> 
> * `python retdec-decompiler.py --help`
>   
>   * In your environment probably something like this (I'm guessing from the paths in that error message, maybe you will have to fix it a little bit):
>     `C:\Users\x230\AppData\Local\Programs\Python\Python35-32\python.exe D:\GitHub\retdec-v3.3-windows-32b\retdec\bin\retdec-decompiler.py --help`
> * `python retdec-decompiler.py x86_crackme_hash.exe`
>   
>   * `C:\Users\x230\AppData\Local\Programs\Python\Python35-32\python.exe D:\GitHub\retdec-v3.3-windows-32b\retdec\bin\retdec-decompiler.py D:\examples\x86_crackme_hash.exe`
> 
> If it works, we will try some more things. If it does not, please paste here what is says.

**Running alone looks like there is no problem, but there is an error message, I don't know if it is the reason.**

> `##### Trying to unpack D:\examples\x86_crackme_hash.exe into D:\examples\x86_crackme_hash-unpacked.tmp by using generic unpacker...
> RUN: D:\GitHub\retdec-v3.2-windows-32b\retdec\bin\retdec-unpacker D:\examples\x86_crackme_hash.exe -o D:\examples\x86_crackme_hash-unpacked.tmp --max-memory-half-ram
> No matching plugins found for 'Microsoft Linker 12.0'
> No matching plugins found for 'MSVC'
> ##### Unpacking by using generic unpacker: nothing to do
> ##### 'upx' not available: nothing to do`

![ConEmu_MTE0WWw4v0](https://user-images.githubusercontent.com/356742/54677557-18583400-4b3e-11e9-9df4-683fe1cc59e1.png)

![ConEmu_85cOB3NgKJ](https://user-images.githubusercontent.com/356742/54677195-5a34aa80-4b3d-11e9-9de3-d6d11d5caf36.png)
![ConEmu_488FX1Ul39](https://user-images.githubusercontent.com/356742/54677196-5acd4100-4b3d-11e9-9f1f-fdd43c2759b3.png)
![ConEmu_CE5PA0N9PM](https://user-images.githubusercontent.com/356742/54677198-5b65d780-4b3d-11e9-92f9-89358b742fa5.png)

**Comment by perfectswpuboy1** [comment]
>
//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2019 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>

// ------------------- Function Prototypes --------------------

int32_t function_401000(char * a1);

// --------------------- Global Variables ---------------------

char (*g1)[6] = "1>=&1";

// ------------------------ Functions -------------------------

// Address range: 0x401000 - 0x40105c
int32_t function_401000(char * a1) {
    char v1 = *a1; // 0x4010265
    if (v1 == 0) {
        // 0x401054
        return 0xabcd;
    }
    int32_t v2 = *(int32_t *)&g1;
    int32_t v3 = 0; // 0x4010238
    char v4 = *(char *)((int32_t)(0x100000000 * (int64_t)(v3 >> 31) % 5) + v2); // 0x401046
    int32_t result = (int32_t)(v4 ^ v1) + 0xabcd; // 0x40104c
    int32_t v5 = v3 + 1; // 0x40101a
    char v6 = *(char *)(v5 + (int32_t)a1); // 0x401026
    // branch -> 0x40102d
    while (v6 != 0) {
        // 0x40102d
        v3 = v5;
        v4 = *(char *)((int32_t)((0x100000000 * (int64_t)(v3 >> 31) | (int64_t)v5 & 0xffffffff) % 5) + v2);
        result += (int32_t)(v4 ^ v6);
        v5 = v3 + 1;
        v6 = *(char *)(v5 + (int32_t)a1);
        // continue -> 0x40102d
    }
    // 0x401054
    return result;
}

// Address range: 0x401060 - 0x4010b7
int main(int argc, char ** argv) {
    int32_t result = -1;
    if (argc == 2) {
        int32_t v1 = function_401000((char *)*(int32_t *)((int32_t)argv + 4)); // 0x40107e
        if (v1 != 0xad6d) {
            // 0x4010a2
            printf("loose\n");
            // branch -> 0x4010b0
        } else {
            // 0x401092
            printf("Win\n");
            // branch -> 0x4010b0
        }
        // 0x4010b0
        result = v1;
        // branch -> 0x4010b3
    }
    // 0x4010b3
    return result;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: microsoft linker (12.0)
// Detected functions: 2
// Decompilation date: 2019-03-20 18:16:00

**Comment by PeterMatula** [comment]
Ok, it looks like RetDec itself is working.
No, that message about not available UPX is not critical and can be ignored.

Now, we will try to determine if something goes wrong with the decompilation itself, or if the problem is in IDA plugin. 
Trigger decompilation from IDA plugin - it will fail, but it will generate the needed files (e.g. config file `x86_crackme_hash.idb.json`) and it will show that error message you posted. Copy (or rewrite) the full command that is being run by `launch_process(command)` and try to run it manually - i.e. run `C:\Users\x230\AppData\Local\Programs\Python\Python35-32\python.exe "D:\GitHub\retdec-v3.3-windows-32b\retdec\bin\retdec-decompiler.py" "D:\examples\x86_crackme_hash.exe" --config="..." --color-for-ida -o "..." --select-decode-only --select-ranges="..."`.

Does it fail, or does it work? If it fails, what does it say?

**Comment by perfectswpuboy1** [comment]
> Ok, it looks like RetDec itself is working.
> No, that message about not available UPX is not critical and can be ignored.
> 
> Now, we will try to determine if something goes wrong with the decompilation itself, or if the problem is in IDA plugin.
> Trigger decompilation from IDA plugin - it will fail, but it will generate the needed files (e.g. config file `x86_crackme_hash.idb.json`) and it will show that error message you posted. Copy (or rewrite) the full command that is being run by `launch_process(command)` and try to run it manually - i.e. run `C:\Users\x230\AppData\Local\Programs\Python\Python35-32\python.exe "D:\GitHub\retdec-v3.3-windows-32b\retdec\bin\retdec-decompiler.py" "D:\examples\x86_crackme_hash.exe" --config="..." --color-for-ida -o "..." --select-decode-only --select-ranges="..."`.
> 
> Does it fail, or does it work? If it fails, what does it say?


-----------
I've run it manually,seems it's works.So I don't understand why doesn't work in IDA.

![retdec_转](https://user-images.githubusercontent.com/356742/54754661-fda9bc00-4c1e-11e9-8a27-e61b24cfee64.gif)
### If possible, you can use Teamviewer to remotely operate my computer to determine if there is something wrong with my IDA configuration.

**Comment by s3rvac** [comment]
I have just noticed that the command in the IDA error window is different from the one that you have tried to run manually:

![different-command](https://user-images.githubusercontent.com/5675953/54816335-4a7baa00-4c94-11e9-9f9e-b38d96a410cd.png)

Even the input files are different. Could you please try running the _exact_ same command as in the IDA error window?

Also, could you please provide the following information?
* What version of IDA do you use?
* What version of `retdec-idaplugin` do you use?
* What version of Windows do you use?

**Comment by perfectswpuboy1** [comment]
What version of IDA do you use?   : 7.0
What version of retdec-idaplugin do you use? : v3.3(3.2 the same error)
What version of Windows do you use? :win7 SP1 Ultimate
![ret-dec-_jq_转](https://user-images.githubusercontent.com/356742/54840955-20b09a80-4d09-11e9-8415-283fdbb71bd1.gif)
I noticed that there is no .c file output.
![explorer_Z6j1KHO9Wf](https://user-images.githubusercontent.com/356742/54860752-a9572700-4d59-11e9-849f-36bf242df006.png)

**Comment by fubuki8087** [comment]
It seems that this problem is caused by Chinese character. When the file you reverse is put in the path that has Chinese character, it raises this error. I meet the same problem, but if I move the file to English path, it works.

**Comment by perfectswpuboy1** [comment]
> It seems that this problem is caused by Chinese character. When the file you reverse is put in the path that has Chinese character, it raises this error. I meet the same problem, but if I move the file to English path, it works.

Thank for replay,But there is absoluty English Path.

**Comment by PeterMatula** [comment]
After 3503eb6, plugin no longer uses launch_process. Release v1.0 will come shortly.
