### ISSUE TITLE
retdec-idaplugin fails to start on ida pro 7.2

### ISSUE THREAD

**Issue by jibanes** [avast-tl/retdec-idaplugin#38]
I select a function, activate the plugin, I see on the console (linux-x86_64, idapro 7.2)
$ ida64
```Python 3.5.3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
```
The GUI seems to be frozen, no refresh, the only option is to ctrl-c.

I have retdec-decompiler.py in the PATH; along with retdec-3.3 installed at usual places.

**Comment by s3rvac** [comment]
Hi. Since you have closed the issue, we assume that you have fixed the problem. Can you please write what you have done to fix it? It may be helpful to other users in the future.

**Comment by jibanes** [comment]
I was missing pygments.
