### ISSUE TITLE
Some questions about Selective Decompilation

### ISSUE THREAD

**Issue by kiritowch** [avast-tl/retdec-idaplugin#4]
Does it have the ability to set the only mode, the same as in the API. For example, sel_decomp_ranges='0x81089BE0-0x81089D70', sel_decomp_decoding='only'

Because my file is too big, I need this only mode, I don't know whether I can do this in IDA, thank you!

https://retdec.com/api/docs/guides.html#what-to-decode

**Comment by Manouchehri** [comment]
Yes. https://github.com/avast-tl/retdec-idaplugin/blob/c4d90268bf49d78e62c7267125553e2559e8fb45/src/idaplugin/decompiler.cpp#L431

See the `Configuration` section in the user guide.

**Comment by PeterMatula** [comment]
Yes, as @Manouchehri wrote, `--select-decode-only` should be used in local decompilation mode each time some range is selected. This should speed up the decompilation process. Does it work for you, or is it too slow even with this? If it is slow, is API decompilation faster? Can you paste here the local decompilation command (should be printed in IDA log window).
