### ISSUE TITLE
Decompilation error

### ISSUE THREAD

**Issue by mendax47** [avast-tl/retdec-idaplugin#40]
Having This Problem For A 64bit PE File

![image](https://user-images.githubusercontent.com/6140928/60067483-96733a80-972c-11e9-80d4-6daf0a070896.png)

![image](https://user-images.githubusercontent.com/6140928/60065912-3ded6e80-9727-11e9-8e40-87a58fdfe8c6.png)

Hexray Looks Fine: 
![image](https://user-images.githubusercontent.com/6140928/60065995-8dcc3580-9727-11e9-96f9-6b44d8b4a4b0.png)

On The Other hand this seems ok

![image](https://user-images.githubusercontent.com/6140928/60065954-62494b00-9727-11e9-8be4-5422fde7ae1f.png)

**Comment by s3rvac** [comment]
(I have moved this issue from [avast/retdec](https://github.com/avast/retdec) to [avast/retdec-idaplugin](https://github.com/avast/retdec-idaplugin) as the issue concerns our IDA plugin.)

**Comment by silverbacknet** [comment]
I'd run the exact commandline in the error message in a command window and see what it tells you and when it fails, hopefully the dialog allows you to just ctrl-c to copy it (standard ones do). Watch the memory usage, as well.

**Comment by PeterMatula** [comment]
@mendax47 can you try what @silverbacknet suggested?

**Comment by mendax47** [comment]
##### Checking if file is a Mach-O Universal static library...

##### Checking if file is an archive...
RUN: D:\retdec\bin\retdec-ar-extractor C:\Users\***\Desktop\Test\GGDEMO\GGDEMO.exe --arch-magic
Not an archive, going to the next step.

##### Gathering file information...
RUN: D:\retdec\bin\retdec-fileinfo -c C:\Users\***\Desktop\Test\GGDEMO\GGDEMO.exe.json --similarity C:\Users\Mendax47\Desktop\Test\GGDEMO\GGDEMO.exe --no-hashes=all --crypto D:\retdec\bin\..\share\retdec\support\generic\yara_patterns\signsrch\signsrch.yara --crypto D:\retdec\bin\..\share\retdec\support\generic\yara_patterns\signsrch\signsrch.yarac --max-memory-half-ram
Input file               : C:\Users\***\Desktop\Test\GGDEMO\GGDEMO.exe
File format              : PE
File class               : 64-bit
File type                : Executable file
Architecture             : x86-64
Endianness               : Little endian
Image base address       : 0x140000000
Entry point address      : 0x140001260
Entry point offset       : 0x660
Entry point section name : .text
Entry point section index: 0
Bytes on entry point     : 4883ec28e8bf0200004883c428e97afeffffcccc4883ec28e83308000085c0742165488b042530000000488b4808eb05483b
Detected tool            : MSVC (compiler), 34 from 34 significant nibbles (100%)
Detected tool            : Microsoft (linker), dos header style
Rich header offset       : 0x80
Rich header key          : 0x2a1ac2b2
Rich header signature    : 0104646f0000000a0103646f000000050105646f0000008d0101646f00000002010568520000002601046852
                           0000001001036852000000080101698400000003000100000000005201056984000000020100698400000001
                           00ff6984000000010102698400000001
Overlay offset           : 0x9ee00
Overlay size             : 0x1d30
Overlay entropy          : 7.323

##### Trying to unpack C:\Users\***\Desktop\Test\GGDEMO\GGDEMO.exe into C:\Users\***\Desktop\Test\GGDEMO\GGDEMO.exe-unpacked.tmp by using generic unpacker...
RUN: D:\retdec\bin\retdec-unpacker C:\Users\***\Desktop\Test\GGDEMO\GGDEMO.exe -o C:\Users\***\Desktop\Test\GGDEMO\GGDEMO.exe-unpacked.tmp --max-memory-half-ram
No matching plugins found for 'MSVC'
No matching plugins found for 'Microsoft'
##### Unpacking by using generic unpacker: nothing to do
##### 'upx' not available: nothing to do

##### Decompiling C:\Users\***\Desktop\Test\GGDEMO\GGDEMO.exe into C:\Users\***\Desktop\Test\GGDEMO\GGDEMO.exe.bc...
RUN: D:\retdec\bin\retdec-bin2llvmir -provider-init -decoder -verify -x87-fpu -main-detection -idioms-libgcc -inst-opt -cond-branch-opt -syscalls -stack -constants -param-return -local-vars -inst-opt -simple-types -generate-dsm -remove-asm-instrs -class-hierarchy -select-fncs -inst-opt -x86-addr-spaces -value-protect -instcombine -tbaa -targetlibinfo -basicaa -domtree -simplifycfg -domtree -early-cse -lower-expect -targetlibinfo -tbaa -basicaa -globalopt -mem2reg -instcombine -simplifycfg -basiccg -domtree -early-cse -lazy-value-info -jump-threading -correlated-propagation -simplifycfg -instcombine -simplifycfg -reassociate -domtree -loops -loop-simplify -lcssa -loop-rotate -licm -lcssa -instcombine -scalar-evolution -loop-simplifycfg -loop-simplify -aa -loop-accesses -loop-load-elim -lcssa -indvars -loop-idiom -loop-deletion -memdep -gvn -memdep -sccp -instcombine -lazy-value-info -jump-threading -correlated-propagation -domtree -memdep -dse -dce -bdce -adce -die -simplifycfg -instcombine -strip-dead-prototypes -globaldce -constmerge -constprop -instnamer -domtree -instcombine -instcombine -tbaa -targetlibinfo -basicaa -domtree -simplifycfg -domtree -early-cse -lower-expect -targetlibinfo -tbaa -basicaa -globalopt -mem2reg -instcombine -simplifycfg -basiccg -domtree -early-cse -lazy-value-info -jump-threading -correlated-propagation -simplifycfg -instcombine -simplifycfg -reassociate -domtree -loops -loop-simplify -lcssa -loop-rotate -licm -lcssa -instcombine -scalar-evolution -loop-simplifycfg -loop-simplify -aa -loop-accesses -loop-load-elim -lcssa -indvars -loop-idiom -loop-deletion -memdep -gvn -memdep -sccp -instcombine -lazy-value-info -jump-threading -correlated-propagation -domtree -memdep -dse -dce -bdce -adce -die -simplifycfg -instcombine -strip-dead-prototypes -globaldce -constmerge -constprop -instnamer -domtree -instcombine -inst-opt -simple-types -stack-ptr-op-remove -idioms -global-to-local -dead-global-assign -instcombine -inst-opt -idioms -phi2seq -value-protect -disable-inlining -disable-simplify-libcalls -config-path C:\Users\Mendax47\Desktop\Test\GGDEMO\GGDEMO.exe.json -max-memory-half-ram -o C:\Users\***\Desktop\Test\GGDEMO\GGDEMO.exe.bc
Running phase: Initialization ( 0.02s )
Running phase: LLVM ( 0.04s )
Running phase: Providers initialization ( 0.04s )
Running phase: Input binary to LLVM IR decoding ( 1.77s )

**Comment by s3rvac** [comment]
@mendax47 Would it be possible for you to share the input binary file (`GGDEMO.exe`) with us? Also, how much RAM do you have?

@PeterMatula Can you please take a look at the output above? Although there is no error message, it seems as if `retdec-bin2llvmir` crashed in phase `Input binary to LLVM IR decoding`.

**Comment by PeterMatula** [comment]
After 3503eb67760f7ab3ca42ff89ea484e9395604d88, plugin no longer uses `launch_process`. Release v1.0 will come shortly.
