### ISSUE TITLE
Could ida for macOS use it ?

### ISSUE THREAD

**Issue by MrRtcl** [avast-tl/retdec-idaplugin#43]
I use ida for macOS and I installed this plugin with the user_guide.pdf. I also installed retdec,but now I can't use it in IDA....There is no plugin in my tool

**Comment by MrRtcl** [comment]
It seems like the plugin wasn't loaded

**Comment by s3rvac** [comment]
Hi. Since you have closed the issue, we assume that you have been able to resolve it by yourself. For future reference, can you please describe what you have done to fix it? It may be useful to someone else who stumbles upon it in the future.

**Comment by PeterMatula** [comment]
If you used pre-compiled packages from [Releases](https://github.com/avast/retdec-idaplugin/releases), they will most certainly not work in macOS. You can try to build the sources yourself, but we do not guarantee it will work. Explanation:
https://github.com/avast/retdec-idaplugin#installation-and-use
