### ISSUE TITLE
Ida 5.x/6.x support

### ISSUE THREAD

**Issue by GregoryMorse** [avast-tl/retdec-idaplugin#45]
Any reason not to create a bunch of macros dealing with the porting to 7.x and allow continued backward compatibility to 5.x/6.x?

I can submit a PR with the change if its worth it.  Mostly just a big conditional compilation blob in defs.h would do the trick, and a small handful of occurrences where class member calls need to be replaced by regular function calls to allow generality.  I am not sure how widespread the IDA 6.x usage is nowadays.

I know things were forward ported but its not difficult to maintain backward compatibility even for the CMake build.  It does not muddy the code too much either.

**Comment by s3rvac** [comment]
@PeterMatula What do you think about this?

**Comment by PeterMatula** [comment]
Well, it could be done, but the answer to _Any reason not to create a bunch of macros_  is:
* _a bunch of macros_
* _a big conditional compilation blob_

@ladislav-zezula have some IDA plugins like this, but when he suggested I could do the same, I said: _HELL NO_. I'm afraid of increased code complexity, i.e. more time and trouble of moving forward. Also, more trouble with potential issues - we don't even currently have IDA 5.x/6.x to reproduce problems when they occur.

All of this could be dealt with of course, but I think the biggest question is _how widespread the IDA 6.x usage is nowadays_ - i.e. is it even worth it? I don't know.

Soft NO for me at the moment.

**Comment by ladislav-zezula** [comment]
Most problematic for maintaining backward compatibility in IDA is that Hex-Rays doesn't really keep the API backward compatible. API names change, API parameters change, also the layout of the structures change.

Basically the only way to deal with it is to create a wrapper module for each IDA version with API incompatible with the other versions. I've been maintaining a debugger plugin for IDA 6.60 to 7.03 and it's a pain in the butt.

**Comment by PeterMatula** [comment]
This is no longer possible, the new plugin version 1.0 will require IDA SDK 7.5.
