### ISSUE TITLE
Use RetDec's JSON output for syntax highlighting

### ISSUE THREAD

**Issue by PeterMatula** [avast-tl/retdec-idaplugin#48]
Right now, IDA plugin runs RetDec with `--color-for-ida` option to get a highlighted C output that it displays to users.

This option will be dropped in the next RetDec release. Instead, RetDec will be able to generate a [JSON C output](https://github.com/avast/retdec/wiki/Decompiler-outputs), which should be used instead.

**Comment by op0x59** [comment]
i dont even get syntax highlighting https://i.imgur.com/0zq2Rwk.png

**Comment by s3rvac** [comment]
@op0x59 Ensure that you have [pygments](http://pygments.org/) installed in your system, as described in the [user guide](https://github.com/avast/retdec-idaplugin/raw/master/doc/user_guide/user_guide.pdf):

![ida-plugin-docs-pygments](https://user-images.githubusercontent.com/5675953/66181593-b2fb0900-e671-11e9-9ce7-e8a259561717.png)

This library is used for syntax highlighting. You can install it via
```
pip install pygments
```
(Ensure that `pip` runs `pip` for Python 2. If not, use `pip3`.)

**Comment by PeterMatula** [comment]
Fixed in 3503eb67760f7ab3ca42ff89ea484e9395604d88. Release v1.0 will come shortly.
