### ISSUE TITLE
Error when adding plugin to IDA Freeware 7.0

### ISSUE THREAD

**Issue by trsh** [avast-tl/retdec-idaplugin#52]
LoadLibrary(C:\Program Files\IDA Freeware 7.0\plugins\retdec64.dll) error: The specified procedure could not be found.
C:\Program Files\IDA Freeware 7.0\plugins\retdec64.dll: can't load file

**Comment by s3rvac** [comment]
[README](https://github.com/avast/retdec-idaplugin#retdec-ida-plugin) clearly states that
> The plugin does NOT work with IDA 6.x, or freeware version of IDA 7.0.

For a list of issues with the freeware version of IDA 7.0, see #22.

**Comment by trsh** [comment]
Sorry
