### ISSUE TITLE
Loading of output C file FAILED on Mac

### ISSUE THREAD

**Issue by securebluefox** [avast-tl/retdec-idaplugin#56]
I tried to build and run the plugin on my Mac. Plugin load seems okay but when I tried to ^D on a function, I still get the error as #29 :
![](http://img.lhyerror404.cn/error404/2020-03-02-122341.png)
The out from IDA's console is
![](http://img.lhyerror404.cn/error404/2020-03-02-122445.png)
from the #29 I can't find any solution。
By the way, I used the latest code to build。
I use this [file](https://github.com/hongriSec/CTF-Training/raw/master/2018/2018%E7%BD%91%E9%BC%8E%E6%9D%AF%E7%AC%AC4%E5%9C%BA/Pwn/ipowtn_e912ff8757c402c8afcc362148836c6c.zip) to test .

**Comment by securebluefox** [comment]
Sorry, I forgot to explain my system information , it is ：
OS version：macOS Catalina 10.15.3
IDA SDK version：7.0
IDA version：7.0

**Comment by PeterMatula** [comment]
Issue is no longer valid. [v1.0](https://github.com/avast/retdec-idaplugin/releases/tag/v1.0) does not use Python and works only in IDA 7.5 with SDK 7.5.
