### ISSUE TITLE
retdec 4.0 unrecognized arguments

### ISSUE THREAD

**Issue by alt-fox** [avast-tl/retdec-idaplugin#58]
New version retdec don't have option **--color-for-ida**

![image](https://user-images.githubusercontent.com/32519709/78763592-01c18c80-798e-11ea-82b9-21cafc3d988d.png)
and
![image](https://user-images.githubusercontent.com/32519709/78763720-30d7fe00-798e-11ea-82bf-f97fc065dde3.png)

**Comment by alt-fox** [comment]
I have already found a discussion of this error:
https://github.com/avast/retdec-idaplugin/issues/48

**Comment by PeterMatula** [comment]
You are probably using IDA plugin `v0.9` with RetDec `v4.0`. IDA plugins are always fixed to some concrete version of RetDec. In this case to `v3.3`. You cannot use it with `v4.0`.

Option `--color-for-ida` is gone and won't be back. The upcoming IDA plugin version `v1.0` will work with RetDec `v4.0`, won't need `--color-for-ida`, and will have plenty of other cool features - I made a huge progress in utilizing IDA SDK :-)

**Comment by PeterMatula** [comment]
I will leave this open unit this incompatibility is fixed with the new plugin version - so that it is more visible for others.

**Comment by PeterMatula** [comment]
In the end, the new plugin will be release right after IDA 7.5 is released - there is some bug in 7.3 and 7.4 that makes the plugin crash. It will be fixed in 7.5.

**Comment by PeterMatula** [comment]
Fixed in 3503eb67760f7ab3ca42ff89ea484e9395604d88. Release v1.0 will come shortly.
