### ISSUE TITLE
lauch_process ...  failed with error code 2

### ISSUE THREAD

**Issue by danyhm** [avast-tl/retdec-idaplugin#59]
Hello,
I installed retdec and IDA plugin. I get this error when i press Ctrl+D
![error](https://user-images.githubusercontent.com/21024667/78814235-8db1d380-79e3-11ea-8f2b-37e20645f547.png)

![error2](https://user-images.githubusercontent.com/21024667/78814246-90142d80-79e3-11ea-80d8-203574bd93b8.png)

I installed python 3.8.2 and retdec v4 with IDA plugin 0.9
my OS is windows 7
I ran retdec-decompiler.py with a sample exe with no errors so I think this is a plugin error
note : my exe is in drive C while retdec and python are in drive D.

**Comment by PeterMatula** [comment]
Yeah, you will have to wait for a few days to use RetDec v4.0 in IDA plugin. See #58 and #48.

**Comment by danyhm** [comment]
update :
I tried running the command that the plugin runs from IDA and noticed there's no option `--color-for-ida` in the help of retdec-decompiler.py

**Comment by danyhm** [comment]
@PeterMatula oh ok thanks !

**Comment by PeterMatula** [comment]
Looks like it will be a good idea to add some version compatibility check into the plugin - I will do that for `v1.0`.

I will leave this open unit this incompatibility is fixed with the new plugin version - so that it is more visible for others.

**Comment by PeterMatula** [comment]
In the end, the new plugin will be release right after IDA 7.5 is released - there is some bug in 7.3 and 7.4 that makes the plugin crash. It will be fixed in 7.5.

**Comment by PeterMatula** [comment]
After 3503eb67760f7ab3ca42ff89ea484e9395604d88, plugin no longer uses `launch_process`. Release v1.0 will come shortly.
