### ISSUE TITLE
launch_process(...) failed with error code 1

### ISSUE THREAD

**Issue by ishroudd** [avast-tl/retdec-idaplugin#60]
IDA Version : 7.0
retdec-idaplugin version : v0.9
retdec version: v3.3
Windows version: 10

I get the following errors trying to run a decompile:

![Error](https://user-images.githubusercontent.com/41129603/80437622-e5db4780-88b6-11ea-985c-8905109ae2b9.png)
![Error2](https://user-images.githubusercontent.com/41129603/80437628-e83da180-88b6-11ea-93de-4b01d27fdf0a.png)

Running the command given in the error in a cmd manually gives:

![Error3](https://user-images.githubusercontent.com/41129603/80438611-6c912400-88b9-11ea-9adf-3a600290e1a5.png)

Interestingly, running the command without the --select-decode-only and --select-ranges options appears to start going through the process, I don't know if it's relevant without the options set though:

![Error4](https://user-images.githubusercontent.com/41129603/80439107-99920680-88ba-11ea-9671-e7d3ef81258e.png)

**Comment by PeterMatula** [comment]
Thanks for the report. I started work on using RetDec as a library. It is going well. The next plugin release will not launch processes, etc. It will be self-contained and these kinds of problems should be non-existent.

**Comment by PavelKotov1** [comment]
Hello, dear friends!
I am not sure if my issue is similar to the one discussed here so I apologize in advance for possibly misplacing my question.
When I run:
C:\Users\root\AppData\Local\Programs\Python\Python38\python.exe D:\retDEC_v3.2\scripts\retdec-decompiler.py --help
everything works just fine, but
C:\Users\root\AppData\Local\Programs\Python\Python38\python.exe D:\retDEC_v3.2\scripts\retdec-decompiler.py C:\crackme.exe 
it fails in the subprocess.py in _executechild startup info
# Start the process
            try:
                hp, ht, pid, tid = _winapi.CreateProcess(executable, args, etc. 
function with "FileNotFoundError" the system cannot find the file specified.
I tried different python versions (from 2.7 to 3.8) but the net result is pretty much the same.
My COMSPEC = C:\Windows\System32\cmd.exe, just in case.
Shell I wait for the RetDec as a library solution, mentioned above, or hopefully there is an easy one available now?
Thanks in advance!

**Comment by PeterMatula** [comment]
After 3503eb67760f7ab3ca42ff89ea484e9395604d88, plugin no longer uses `launch_process`. Release v1.0 will come shortly.
