### ISSUE TITLE
retdec not loading

### ISSUE THREAD

**Issue by Jirubizu** [avast-tl/retdec-idaplugin#61]
I am unsure what you would like me to provide in terms of logs. However, the plugin loaded one time and after a restart it did not load at all. It doesnt recognise any of the keybindings nor do I find any reference of the plugin anywhere in IDA.

Not sure for the cause

**Comment by PeterMatula** [comment]
1. Did it work the first time?
2. Is the plugin still in the IDA plugin directory?
3. Did you update IDA or something like that?

**Comment by PeterMatula** [comment]
No reaction -> closing.
Moreover, the issue is probably no longer valid since the release of [v1.0](https://github.com/avast/retdec-idaplugin/releases/tag/v1.0).
