### ISSUE TITLE
How to compile the c file generated by retdec-idaplugin?

### ISSUE THREAD

**Issue by leibo-hust** [avast-tl/retdec-idaplugin#62]
Hi, I can successfully use the this plugin to generate `c` files, but how to compile this c file to regenerate the executable file? I directly use the **`gcc hello.exe.c -o hello-d`** command, but it doesn't seem to work. What parameters should be added? Thank you

**Comment by PeterMatula** [comment]
Hi, RetDec's output is not really meant for re-compilation. It aims to produce C code that could be analyzed by human reverse engineers. It is very hard to decompile a binary into a C source code that:
1. could be compiled without errors
2. would do the same thing as the original binary

Although RetDec sometimes may produce an output where this is possible, most of the times it does not. If by any change it does, you should be able to compile it just like any other C source code.

If you are interested in re-compilation, take a look at https://github.com/lifting-bits/mcsema.
