### ISSUE TITLE
Continued support for IDA 7.2-7.4

### ISSUE THREAD

**Issue by galaxyhaxz** [avast-tl/retdec-idaplugin#67]
Most people aren't gifted with the privilege of working a nice cozy tech job in security where their employer just so happens to buy them the latest version of IDA. Most people work crappy jobs with crappy pay and getting the latest IDA is out of reach/impossible.

Therefore, would be nice to support older versions for a little bit longer. Not sure if it's as simple as compiling against an older SDK/macros, though.

**Comment by paxcut** [comment]
You are right about being able to afford the latest IDA version. Getting this plugin to work on IDA 7.0-7.4 is doable, but you can't expect the latest version of the plugin, as it uses features that are exclusive to IDA 7.5. 
If you don't mind using an earlier version get  0.9 and retdec 3.3 and that should work fine on the targeted IDA versions. I got it to work but I had to make some changes to the source code. My friend got it to work without changes (related to using launch_process to spawn python3).
I don't expect  support for older IDAs to come back, but having source code and access to its entire history is the next best thing and I for one am grateful for it.

**Comment by galaxyhaxz** [comment]
Agreed, the joys of git and modern day source code control. I'll look into it. I'm not in dire straits or anything, as I have ghidra to fallback on but it's decompiler (mips and ppc) are still quite in their infancy, so having something to compare against would save time of manually reversing functions. Given the project I'm working on is reversing code to recompile it ;)
