### ISSUE TITLE
The compiled version from release doees not work

### ISSUE THREAD

**Issue by gjf** [avast-tl/retdec-idaplugin#69]
IDA 7.7 SP1 output when started:
LoadLibrary(..\Program Files\Analysis\HEX\IDA\IDA 77SP1\plugins\retdec64.dll) error: Cannot find a module
..\Program Files\Analysis\HEX\IDA\IDA 77SP1\plugins\retdec64.dll: can't load file

**Comment by PeterMatula** [comment]
Well, I don't have an IDA 7.7, I tested only 8.0, and only on my local machine which built the libs so it is not super reliable to check it will work everywhere.

But after your issue, I tried to use 7.7 build in my 8.0 IDA and it worked, so it cannot (shouldn't?) be completely bad. I'm thinking some differences in OS environment:
* I'm using Windows 11, what do you use? 
* In these new builds I forced static runtime for Windows for the first time - it should require fewer dependencies than before. But there are still these:
  ```
  Image has the following dependencies:

    ida64.dll
    libcrypto-3-x64.dll
    KERNEL32.dll
    SHELL32.dll
    ole32.dll
    ADVAPI32.dll
  ```
   Maybe you are missing [OpenSSL 3](https://slproweb.com/products/Win32OpenSSL.html) (or [this](https://kb.firedaemon.com/support/solutions/articles/4000121705-openssl-3-0-and-1-1-1-binary-distributions-for-microsoft-windows))? Could you try to install it and see if it helps? If it helps I will make sure it is mentioned in some visible place.

**Comment by gjf** [comment]
Thanks or a prompt reaction.

Yes you were right: copying libcrypto-3-x64.dll into IDA folder solved the problem. However Win64OpenSSL_Light-3_0_5 was installed in the system and included in PATH variables so no idea what was wrong.

Anyway the problem is solved now, thank you. I really think OpenSSL 3 requirements should be also included in installation manual...

**Comment by PeterMatula** [comment]
Thanks for trying it and getting back. I will make sure this requirement is well visible.

**Comment by PeterMatula** [comment]
I mentioned OpenSSL in the user guide and updated the releases. I also mentioned it in the release description and Readme.
