### ISSUE TITLE
Automatically install or produce release packages containing retdec

### ISSUE THREAD

**Issue by PeterMatula** [avast-tl/retdec-idaplugin#8]
Right now, if users/developers want to use `retdec-idaplugin` in local decompilation mode with `retdec`, they need to either get the pre-compiled `retdec` package, or build and install it themselves. Then whey need to configure `retdec-idaplugin` in order to use local decompilation.

This could be made much easier - `retdec-idaplugin` could take care of everything:
- CMake could take option that would cause it to get, build and install `retdec` alongside `retdec-idaplugin`.
- Such a build and installation could be pre-configured -> working out-of-the-box local decompilation.
- There could be a script, that automatically takes this and creates a binary release containing both `retdec-idaplugin` and `retdec`.
- Anyone using such a release package would only need to unpack it and copy it to IDA -> local decompilation would work out-of-the-box.

**Comment by s3rvac** [comment]
Just a note so we do not forget: Users will still need to install Python 3 (+ [pygments](http://pygments.org/)) as IDA ships only with Python 2 and RetDec requires Python 3 to run.

**Comment by PeterMatula** [comment]
Fixed in 3503eb67760f7ab3ca42ff89ea484e9395604d88. Release v1.0 will come shortly.
